del dump.tmp
parser test1.pas > dump.tmp
parser test2.pas >> dump.tmp
parser test3.pas >> dump.tmp
parser test4.pas >> dump.tmp
parser test5.pas >> dump.tmp
parser test6.pas >> dump.tmp
parser test7.pas >> dump.tmp
parser test8.pas >> dump.tmp
parser test9.pas >> dump.tmp
parser test10.pas >> dump.tmp
parser test11.pas >> dump.tmp
parser test12.pas >> dump.tmp
parser test13.pas >> dump.tmp
parser test14.pas >> dump.tmp
parser test15.pas >> dump.tmp


