
/* Positions of the Window popups in the menu bars */
#define INPUT_MENU_WINDOW_POS           4
#define OUTPUT_MENU_WINDOW_POS          1

/* Icons */
#define ICO_MAIN                        10
#define ICO_INPUT                       11
#define ICO_OUTPUT                      12

/* Main menus IDs*/
#define IDR_FRAME                       101
#define IDR_INPUT                       102
#define IDR_OUTPUT                      103
                 
/* Error strings */                 
#define IDS_ERR_INPUT_EDIT_SPACE        200
#define IDS_ERR_INPUT_FILE_READ         201
#define IDS_ERR_INPUT_SAVE_FAIL         202
#define IDS_ERR_INPUT_TEXT_NOT_FOUND    203
#define IDS_ERR_INPUT_REGISTER          204
#define IDS_ERR_INPUT_MENU              205
#define IDS_ERR_INPUT_CREATE            206
#define IDS_ERR_INPUT_CREATE_EDIT       207
#define IDS_ERR_INPUT_FILE_LOAD         208

#define IDS_ERR_FRAME_REGISTER          224               
#define IDS_ERR_FRAME_NULL_MENU         225
#define IDS_ERR_FRAME_CREATE            226
#define IDS_ERR_FRAME_CREATE_CLIENT     227

#define IDS_ERR_OUTPUT_REGISTER         240
#define IDS_ERR_OUTPUT_MENU             241


#define IDS_ERR_MAIN_ACCEL              256
#define IDS_ERR_MAIN_OUTPUT_BUFFER      257
#define IDS_ERR_MAIN_INIT_INTERP        258
 
/* Popups */                   
#define ID_FILE_INPUT                   512
#define ID_FILE_OUTPUT                  513
#define ID_FILE_RUN                     514
#define ID_FILE_EXIT                    515
#define ID_FILE_OPEN                    516
#define ID_FILE_SAVEAS                  518
#define ID_FILE_CLOSE                   519
#define ID_FILE_LOAD                    520

#define ID_EDIT_UNDO                    528
#define ID_EDIT_CUT                     529
#define ID_EDIT_COPY                    530
#define ID_EDIT_PASTE                   531
#define ID_EDIT_SELECTALL               532
#define ID_EDIT_DELETE                  533

#define ID_SEARCH_FIND                  544
#define ID_SEARCH_FINDNEXT              545
#define ID_SEARCH_REPLACE               546

#define ID_WINDOW_CASCADE               560
#define ID_WINDOW_TILE                  561
#define ID_WINDOW_ARRANGEICONS          562
#define ID_WINDOW_CLOSEALL              563

#define ID_RUN_RUN                      576
#define ID_RUN_PAUSE                    577
#define ID_RUN_BREAK                    578

#define ID_HELP_ABOUT                   592

/* Id of first title in current window list */
#define ID_FIRST_CHILD                  1000


